import type { ObjectiveSeed } from "./types";

/** Finance concepts, second batch. */
export const FINANCE_CONCEPTS_MORE: ObjectiveSeed[] = [
  {
    topic: "valuation",
    difficulty: "medium",
    stem: "A perpetuity pays ₹50 lakh a year forever, growing at 3%. At a 11% discount rate its present value is:",
    options: ["₹6.25 crore", "₹4.55 crore", "₹16.67 crore", "₹5.00 crore"],
    answer: "₹6.25 crore",
    explanation: "Gordon growth: PV = CF / (r − g) = 50 / (0.11 − 0.03) = 50/0.08 = ₹625 lakh = ₹6.25 crore.",
  },
  {
    topic: "valuation",
    difficulty: "hard",
    stem: "In a DCF, the terminal value usually accounts for what share of total enterprise value?",
    options: ["60-80%", "10-20%", "30-40%", "Under 10%"],
    answer: "60-80%",
    explanation: "Most of the value sits beyond the explicit forecast, which is why the terminal growth rate and exit multiple deserve more scrutiny than the year-three revenue line everyone argues about.",
  },
  {
    topic: "cost of capital",
    difficulty: "medium",
    stem: "A firm is 40% debt at 9% pre-tax and 60% equity at 15%, with a 25% tax rate. WACC is:",
    options: ["11.7%", "12.6%", "10.8%", "13.2%"],
    answer: "11.7%",
    explanation: "After-tax debt cost = 9% × 0.75 = 6.75%. WACC = 0.4 × 6.75 + 0.6 × 15 = 2.7 + 9.0 = 11.7%.",
  },
  {
    topic: "cost of capital",
    difficulty: "medium",
    stem: "Under CAPM, a stock with beta 1.4, risk-free rate 7% and market risk premium 6% has a cost of equity of:",
    options: ["15.4%", "15.4% only if beta is levered", "13.0%", "8.4%"],
    answer: "15.4%",
    explanation: "Ke = Rf + β × MRP = 7 + 1.4 × 6 = 15.4%. Note the premium is the market return minus the risk-free rate, not the market return itself.",
  },
  {
    topic: "capital budgeting",
    difficulty: "medium",
    stem: "Two mutually exclusive projects have the same NPV but different IRRs. You should choose:",
    options: [
      "Either — NPV is the decision rule and they are equal",
      "The higher IRR always",
      "The shorter payback always",
      "Neither without knowing revenue",
    ],
    answer: "Either — NPV is the decision rule and they are equal",
    explanation: "NPV measures value added in rupees and is the correct rule for mutually exclusive choices. IRR can rank projects differently because it implicitly assumes reinvestment at the IRR.",
  },
  {
    topic: "capital budgeting",
    difficulty: "hard",
    stem: "A project has cash flows −100, +60, +60. Its IRR is closest to:",
    options: ["13%", "20%", "10%", "17%"],
    answer: "13%",
    explanation: "At 13%: 60/1.13 + 60/1.13² = 53.1 + 47.0 = 100.1, so NPV is roughly zero. A common error is averaging the 20% total return over two years.",
  },
  {
    topic: "leverage",
    difficulty: "medium",
    stem: "Interest coverage is EBIT ÷ interest. A firm with EBIT ₹120 crore and debt of ₹500 crore at 10% has coverage of:",
    options: ["2.4x", "4.2x", "1.2x", "0.42x"],
    answer: "2.4x",
    explanation: "Interest = 500 × 10% = ₹50 crore. Coverage = 120/50 = 2.4x. Below about 2x, lenders start attaching covenants.",
  },
  {
    topic: "multiples",
    difficulty: "medium",
    stem: "Enterprise value equals market capitalisation plus:",
    options: [
      "Net debt",
      "Total assets",
      "Gross debt plus cash",
      "Retained earnings",
    ],
    answer: "Net debt",
    explanation: "EV = market cap + debt − cash. Cash is subtracted because an acquirer effectively gets it back to offset the purchase price.",
  },
  {
    topic: "accounting linkage",
    difficulty: "hard",
    stem: "A company raises ₹200 crore of debt and immediately spends it on a factory. The immediate effect on net income is:",
    options: [
      "None in the period of purchase",
      "A fall of ₹200 crore",
      "A rise of ₹200 crore",
      "A fall equal to the interest only",
    ],
    answer: "None in the period of purchase",
    explanation: "Capex is a balance-sheet movement, not an expense; it reaches the income statement later as depreciation. Interest accrues over time rather than on day one, so the immediate effect is nil.",
  },
  {
    topic: "working capital",
    difficulty: "medium",
    stem: "The cash conversion cycle is days inventory plus days receivable minus:",
    options: ["Days payable", "Days cash", "Days sales", "Days capex"],
    answer: "Days payable",
    explanation: "Supplier credit funds part of the cycle, so it is subtracted. A negative cycle — common in retail and quick commerce — means suppliers finance the business.",
  },
  {
    topic: "risk",
    difficulty: "medium",
    stem: "Diversification eliminates which type of risk?",
    options: [
      "Unsystematic risk only",
      "Both systematic and unsystematic",
      "Systematic risk only",
      "Neither",
    ],
    answer: "Unsystematic risk only",
    explanation: "Firm-specific risk can be diversified away. Market-wide risk cannot, which is why only systematic risk (beta) is compensated in CAPM.",
  },
  {
    topic: "deal mechanics",
    difficulty: "hard",
    stem: "An all-stock acquisition is accretive to the acquirer's EPS when:",
    options: [
      "The acquirer's P/E is higher than the target's",
      "The target is larger than the acquirer",
      "The acquirer pays a premium",
      "The target has more cash",
    ],
    answer: "The acquirer's P/E is higher than the target's",
    explanation: "Issuing expensive paper to buy cheaper earnings raises EPS mechanically. Accretion is not the same as value creation — it says nothing about whether the price was worth paying.",
  },
  {
    topic: "ratios",
    difficulty: "medium",
    stem: "ROE can be decomposed (DuPont) into margin × asset turnover ×:",
    options: ["Equity multiplier", "Tax rate", "Interest coverage", "Dividend payout"],
    answer: "Equity multiplier",
    explanation: "ROE = (net income/sales) × (sales/assets) × (assets/equity). The third term is leverage, which is why two firms with identical operations can report very different ROE.",
  },
  {
    topic: "valuation",
    difficulty: "easy",
    stem: "Free cash flow to the firm is EBIT(1−t) plus depreciation minus capex minus:",
    options: [
      "The increase in working capital",
      "Interest expense",
      "Dividends paid",
      "Debt repayment",
    ],
    answer: "The increase in working capital",
    explanation: "FCFF is pre-financing, so interest and debt movements are excluded. Working capital growth consumes cash and must be subtracted.",
  },
];

/** Accounting, second batch. */
export const ACCOUNTING_MORE: ObjectiveSeed[] = [
  {
    topic: "statements",
    difficulty: "easy",
    stem: "Which statement shows performance over a period rather than position at a point in time?",
    options: ["Income statement", "Balance sheet", "Both do", "Neither does"],
    answer: "Income statement",
    explanation: "The balance sheet is a snapshot at a date; the income statement and cash flow statement cover a period.",
  },
  {
    topic: "statements",
    difficulty: "medium",
    stem: "Purchasing inventory on credit affects the balance sheet how?",
    options: [
      "Assets and liabilities both rise",
      "Assets rise, equity rises",
      "Assets fall, liabilities fall",
      "No effect",
    ],
    answer: "Assets and liabilities both rise",
    explanation: "Inventory (asset) and accounts payable (liability) both increase. Equity is untouched because nothing has been earned or spent.",
  },
  {
    topic: "statements",
    difficulty: "hard",
    stem: "A firm reports rising profits and falling operating cash flow for three years. The most likely explanation is:",
    options: [
      "Receivables and inventory are growing faster than sales",
      "It is paying down debt",
      "It is buying back shares",
      "Depreciation has increased",
    ],
    answer: "Receivables and inventory are growing faster than sales",
    explanation: "Profit is accrual, cash is not. A widening gap usually means revenue is being recognised before cash arrives, or stock is piling up. Debt repayment and buybacks sit below operating cash flow, and more depreciation would raise operating cash flow.",
  },
  {
    topic: "ratios",
    difficulty: "medium",
    stem: "Inventory ₹60 lakh, COGS ₹480 lakh a year. Inventory days are approximately:",
    options: ["46", "60", "38", "73"],
    answer: "46",
    explanation: "Inventory days = (inventory / COGS) × 365 = (60/480) × 365 = 45.6, so about 46 days.",
  },
  {
    topic: "ratios",
    difficulty: "medium",
    stem: "Debt ₹300 crore, equity ₹200 crore, EBITDA ₹100 crore. Net debt to EBITDA, assuming ₹50 crore of cash, is:",
    options: ["2.5x", "3.0x", "1.5x", "5.0x"],
    answer: "2.5x",
    explanation: "Net debt = 300 − 50 = ₹250 crore. 250/100 = 2.5x. Equity is irrelevant to this particular ratio.",
  },
  {
    topic: "depreciation",
    difficulty: "medium",
    stem: "An asset costing ₹50 lakh with ₹5 lakh salvage value and a 9-year life is depreciated straight-line at:",
    options: ["₹5 lakh a year", "₹5.56 lakh a year", "₹4.5 lakh a year", "₹5.5 lakh a year"],
    answer: "₹5 lakh a year",
    explanation: "(50 − 5) / 9 = ₹5 lakh. Salvage value is excluded from the depreciable base — forgetting it gives ₹5.56 lakh.",
  },
  {
    topic: "revenue recognition",
    difficulty: "medium",
    stem: "A consultancy completes 40% of a fixed-fee ₹50 lakh project by year end. Under percentage-of-completion it recognises:",
    options: ["₹20 lakh", "₹50 lakh", "Nothing", "₹30 lakh"],
    answer: "₹20 lakh",
    explanation: "Revenue follows delivery, so 40% of ₹50 lakh = ₹20 lakh, regardless of how much has been billed or collected.",
  },
  {
    topic: "provisions",
    difficulty: "hard",
    stem: "A company expects to lose a lawsuit and pay ₹8 crore. It should:",
    options: [
      "Recognise a provision of ₹8 crore",
      "Disclose it but recognise nothing",
      "Wait until payment",
      "Reduce equity directly",
    ],
    answer: "Recognise a provision of ₹8 crore",
    explanation: "A present obligation that is probable and reliably estimable is provided for. Only a possible-but-not-probable obligation is a contingent liability, which is disclosed rather than recognised.",
  },
  {
    topic: "equity",
    difficulty: "medium",
    stem: "A share buyback of ₹100 crore has what effect on the balance sheet?",
    options: [
      "Cash falls ₹100 crore and equity falls ₹100 crore",
      "Cash falls and liabilities fall",
      "Equity rises",
      "No effect on totals",
    ],
    answer: "Cash falls ₹100 crore and equity falls ₹100 crore",
    explanation: "It is a return of capital, so both sides contract. EPS typically rises because the share count falls, not because profit rose.",
  },
  {
    topic: "cash flow",
    difficulty: "medium",
    stem: "Dividends paid appear in which section of the cash flow statement?",
    options: ["Financing", "Operating", "Investing", "They do not appear"],
    answer: "Financing",
    explanation: "Dividends are a distribution to capital providers. Under Ind AS interest paid may be classified as operating or financing, but dividends paid are financing.",
  },
  {
    topic: "goodwill",
    difficulty: "hard",
    stem: "Goodwill on an acquisition arises when:",
    options: [
      "Price paid exceeds the fair value of identifiable net assets",
      "The target is profitable",
      "The acquirer pays in shares",
      "The target has strong brands on its balance sheet",
    ],
    answer: "Price paid exceeds the fair value of identifiable net assets",
    explanation: "It is the residual. Internally generated brands are not on the target's balance sheet, which is part of why a premium arises — but goodwill is defined by the arithmetic, not the reason.",
  },
  {
    topic: "statements",
    difficulty: "easy",
    stem: "Which is NOT a current asset?",
    options: ["Plant and machinery", "Inventory", "Trade receivables", "Prepaid expenses"],
    answer: "Plant and machinery",
    explanation: "Current assets are expected to convert to cash within a year. Plant is a non-current, long-lived asset.",
  },
];

/** Marketing concepts, second batch. */
export const MARKETING_CONCEPTS_MORE: ObjectiveSeed[] = [
  {
    topic: "unit economics",
    difficulty: "medium",
    stem: "Payback period on CAC is CAC divided by:",
    options: [
      "Monthly gross margin per customer",
      "Monthly revenue per customer",
      "Annual revenue per customer",
      "Lifetime value",
    ],
    answer: "Monthly gross margin per customer",
    explanation: "Only the margin repays the acquisition cost, not the full revenue. Using revenue flatters payback by whatever the cost of service is.",
  },
  {
    topic: "unit economics",
    difficulty: "hard",
    stem: "A subscription business has 4% monthly churn. Its average customer lifetime is:",
    options: ["25 months", "4 months", "48 months", "12 months"],
    answer: "25 months",
    explanation: "Lifetime ≈ 1 / churn = 1/0.04 = 25 months. The relationship is convex: halving churn to 2% doubles lifetime to 50 months.",
  },
  {
    topic: "pricing",
    difficulty: "medium",
    stem: "A firm with 30% contribution margin cuts price by 10%. Volume must rise by roughly how much to hold contribution constant?",
    options: ["50%", "10%", "30%", "20%"],
    answer: "50%",
    explanation: "Take price 100, variable cost 70, margin 30. New price 90 gives margin 20. To hold total contribution: 30/20 = 1.5, so volume must rise 50%. Discounting is far more demanding than it looks at low margins.",
  },
  {
    topic: "pricing",
    difficulty: "medium",
    stem: "Price skimming means:",
    options: [
      "Launching high and lowering price over time",
      "Launching low to gain share",
      "Matching the market leader",
      "Charging different prices by segment",
    ],
    answer: "Launching high and lowering price over time",
    explanation: "It captures willingness to pay from early adopters first. Launching low is penetration pricing; charging by segment is price discrimination.",
  },
  {
    topic: "brand",
    difficulty: "medium",
    stem: "Brand equity is best evidenced by:",
    options: [
      "A price premium sustained against comparable substitutes",
      "High advertising spend",
      "High awareness scores",
      "A large social media following",
    ],
    answer: "A price premium sustained against comparable substitutes",
    explanation: "Equity shows up in what people will pay, not in what they have heard of. Awareness is a necessary condition and a poor measure.",
  },
  {
    topic: "brand",
    difficulty: "hard",
    stem: "A brand has 90% awareness, 40% consideration and 8% purchase among considerers. The weakest link is:",
    options: [
      "Conversion from consideration to purchase",
      "Awareness",
      "Consideration",
      "All three are equal",
    ],
    answer: "Conversion from consideration to purchase",
    explanation: "Awareness to consideration loses 56% of those aware; consideration to purchase loses 92% of those considering. The steepest drop is at the final step, so spending on awareness would be the wrong response.",
  },
  {
    topic: "segmentation",
    difficulty: "medium",
    stem: "Which segmentation basis is most likely to predict purchase behaviour?",
    options: [
      "The job the customer is trying to get done",
      "Age band",
      "City tier",
      "Income decile",
    ],
    answer: "The job the customer is trying to get done",
    explanation: "Jobs-to-be-done cuts across demographics: two people of very different ages buying a drill both want a hole. Demographics are easy to measure and weak at prediction.",
  },
  {
    topic: "channels",
    difficulty: "medium",
    stem: "A D2C brand's contribution margin falls sharply after moving to a marketplace. The most likely cause is:",
    options: [
      "Marketplace commission and higher returns",
      "Lower product cost",
      "Reduced advertising",
      "Longer customer lifetime",
    ],
    answer: "Marketplace commission and higher returns",
    explanation: "Marketplaces charge 15-30% and see materially higher return rates than a brand's own site. The trade is reach against margin and against owning the customer relationship.",
  },
  {
    topic: "advertising",
    difficulty: "medium",
    stem: "ROAS of 3.0 on a product with 25% gross margin means the campaign is:",
    options: [
      "Losing money on a contribution basis",
      "Profitable",
      "Breaking even",
      "Impossible to judge without CAC",
    ],
    answer: "Losing money on a contribution basis",
    explanation: "₹100 of spend returns ₹300 of revenue, which carries ₹75 of gross margin — less than the ₹100 spent. Break-even ROAS is 1 ÷ margin = 4.0 here. Judging ROAS without the margin is the most common paid-media error.",
  },
  {
    topic: "retention",
    difficulty: "medium",
    stem: "Cohort retention curves that flatten after month three indicate:",
    options: [
      "A stable core of habitual users has formed",
      "The product is failing",
      "Acquisition is too expensive",
      "Churn is accelerating",
    ],
    answer: "A stable core of habitual users has formed",
    explanation: "A flattening curve means the remaining users have stopped leaving — the asymptote is the real long-term retention. A curve that keeps declining to zero means no durable user base.",
  },
  {
    topic: "distribution",
    difficulty: "hard",
    stem: "Numeric distribution is 40% and weighted distribution is 70%. This means the brand is:",
    options: [
      "In fewer stores, but the larger ones",
      "In more stores, but smaller ones",
      "Equally spread",
      "Losing shelf space",
    ],
    answer: "In fewer stores, but the larger ones",
    explanation: "Numeric counts stores; weighted counts them by category sales. Weighted above numeric means the stores it is in are bigger than average — the usual pattern for a premium brand.",
  },
  {
    topic: "research",
    difficulty: "medium",
    stem: "Ninety per cent of survey respondents say they would buy a new product. Actual launch conversion is 4%. The most likely reason is:",
    options: [
      "Stated intent overstates behaviour when there is no cost to saying yes",
      "The survey sample was too small",
      "The product was priced wrongly",
      "The launch was badly marketed",
    ],
    answer: "Stated intent overstates behaviour when there is no cost to saying yes",
    explanation: "Intent-to-purchase questions routinely overstate. The standard corrections are to discount stated intent heavily or to test with a real commitment — a pre-order, a deposit.",
  },
];

/** Operations and supply chain — the new track (20250101000039). */
export const OPERATIONS_CONCEPTS: ObjectiveSeed[] = [
  {
    topic: "inventory",
    difficulty: "medium",
    stem: "Annual demand 10,000 units, ordering cost ₹400 per order, holding cost ₹20 per unit per year. Economic order quantity is:",
    options: ["632 units", "500 units", "1,000 units", "447 units"],
    answer: "632 units",
    explanation: "EOQ = √(2DS/H) = √(2 × 10,000 × 400 / 20) = √400,000 = 632 units.",
  },
  {
    topic: "inventory",
    difficulty: "easy",
    stem: "Safety stock exists primarily to absorb:",
    options: [
      "Variability in demand and lead time",
      "Seasonal peaks",
      "Supplier price rises",
      "Warehouse rent",
    ],
    answer: "Variability in demand and lead time",
    explanation: "Cycle stock covers expected demand between orders; safety stock covers the variance around it. Seasonality is planned for separately with build-ahead stock.",
  },
  {
    topic: "inventory",
    difficulty: "medium",
    stem: "Inventory turns of 6 correspond to average days of stock of about:",
    options: ["61 days", "6 days", "30 days", "180 days"],
    answer: "61 days",
    explanation: "365 / 6 = 60.8 days. Turns and days are reciprocals of each other — raising turns is the same statement as cutting days of cover.",
  },
  {
    topic: "capacity",
    difficulty: "medium",
    stem: "A line has four sequential stations with capacities 100, 80, 120 and 95 units per hour. Line capacity is:",
    options: ["80 per hour", "95 per hour", "98.75 per hour", "120 per hour"],
    answer: "80 per hour",
    explanation: "A sequential line runs at the rate of its bottleneck. Adding capacity anywhere except the 80-unit station changes nothing.",
  },
  {
    topic: "capacity",
    difficulty: "hard",
    stem: "In the line above, capacity at the bottleneck is doubled to 160. New line capacity is:",
    options: ["95 per hour", "160 per hour", "100 per hour", "120 per hour"],
    answer: "95 per hour",
    explanation: "The bottleneck moves to the next slowest station, 95. Debottlenecking is iterative — the gain from fixing one station is capped by the next.",
  },
  {
    topic: "queuing",
    difficulty: "medium",
    stem: "As utilisation approaches 100%, average waiting time:",
    options: [
      "Rises sharply and without bound",
      "Falls",
      "Stays constant",
      "Rises linearly",
    ],
    answer: "Rises sharply and without bound",
    explanation: "Waiting time is convex in utilisation. This is why hospitals and call centres deliberately plan for 80-85% rather than 100% — the last few points of utilisation cost disproportionate delay.",
  },
  {
    topic: "quality",
    difficulty: "medium",
    stem: "A Six Sigma process corresponds to roughly how many defects per million opportunities?",
    options: ["3.4", "34", "340", "3,400"],
    answer: "3.4",
    explanation: "3.4 DPMO, allowing for the conventional 1.5-sigma long-term shift. Three sigma is about 66,800 DPMO, which is why the jump matters.",
  },
  {
    topic: "quality",
    difficulty: "hard",
    stem: "A process has four sequential steps each with 95% first-pass yield. Overall rolled throughput yield is:",
    options: ["81%", "95%", "80%", "20%"],
    answer: "81%",
    explanation: "0.95⁴ = 0.8145, about 81%. Yields multiply along a chain, which is why long processes with individually good steps still produce a lot of rework.",
  },
  {
    topic: "lean",
    difficulty: "easy",
    stem: "In lean manufacturing, which is NOT one of the classic wastes?",
    options: ["Automation", "Overproduction", "Waiting", "Excess inventory"],
    answer: "Automation",
    explanation: "The classic wastes are overproduction, waiting, transport, over-processing, inventory, motion and defects. Automation is a method, and automating a wasteful process only makes waste faster.",
  },
  {
    topic: "supply chain",
    difficulty: "medium",
    stem: "The bullwhip effect describes:",
    options: [
      "Demand variability amplifying as it moves upstream",
      "Prices falling as volume rises",
      "Lead times shortening with scale",
      "Inventory falling as demand rises",
    ],
    answer: "Demand variability amplifying as it moves upstream",
    explanation: "Small swings at retail become large swings at the supplier, driven by batching, forecasting on orders rather than demand, and reactive safety stock. Sharing point-of-sale data upstream is the standard fix.",
  },
  {
    topic: "supply chain",
    difficulty: "medium",
    stem: "A firm moves from three regional warehouses to one central one. Total safety stock required:",
    options: [
      "Falls, roughly with the square root of the reduction in locations",
      "Falls proportionally",
      "Rises",
      "Is unchanged",
    ],
    answer: "Falls, roughly with the square root of the reduction in locations",
    explanation: "Risk pooling: independent demand variances add, so pooling three locations into one cuts safety stock by about √3, not by two thirds. The offset is longer delivery distance.",
  },
  {
    topic: "cost to serve",
    difficulty: "hard",
    stem: "A distributor's smallest 40% of customers generate 5% of revenue but 25% of delivery cost. The right first response is:",
    options: [
      "Change the service model for those accounts, not necessarily drop them",
      "Drop all of them immediately",
      "Raise prices across all customers",
      "Cut delivery costs everywhere",
    ],
    answer: "Change the service model for those accounts, not necessarily drop them",
    explanation: "Cost to serve is usually fixable with order minimums, delivery frequency or a distributor handoff. Dropping accounts forfeits contribution that may still be positive and can free capacity for a competitor.",
  },
];

/**
 * Business and economy, second batch.
 *
 * Still written around durable structure — which body does what, how a tax or
 * a code works — rather than around headlines. A seeded current-affairs bank
 * goes stale, and a stale current-affairs question is worse than none: it
 * teaches something that has stopped being true. The intended operating model
 * for this track remains a recurring refresh, not this file.
 */
export const CURRENT_AFFAIRS_MORE: ObjectiveSeed[] = [
  {
    topic: "indian economy",
    difficulty: "medium",
    stem: "India's inflation-targeting framework requires the RBI to keep CPI inflation within which band?",
    options: ["4% ± 2%", "2% ± 1%", "6% ± 2%", "5% ± 1%"],
    answer: "4% ± 2%",
    explanation: "A 4% target with a tolerance band of ±2 percentage points. Missing it for three consecutive quarters obliges the RBI to report to the government explaining why.",
  },
  {
    topic: "indian economy",
    difficulty: "easy",
    stem: "Which measure of inflation does the RBI target for monetary policy?",
    options: ["Consumer Price Index", "Wholesale Price Index", "GDP deflator", "Producer Price Index"],
    answer: "Consumer Price Index",
    explanation: "CPI, since the 2016 framework. WPI is still published and watched for input-cost pressure but is not the policy target.",
  },
  {
    topic: "capital markets",
    difficulty: "medium",
    stem: "In an IPO, the anchor investor portion is allotted:",
    options: [
      "A day before the issue opens to the public",
      "After the public issue closes",
      "At the same time as retail allotment",
      "Only if the issue is undersubscribed",
    ],
    answer: "A day before the issue opens to the public",
    explanation: "Anchor allotment happens one day prior and is disclosed, which is why the anchor book is read as a signal of institutional appetite before bidding opens.",
  },
  {
    topic: "capital markets",
    difficulty: "hard",
    stem: "A company's promoters hold 74%. To remain listed under Indian rules they must:",
    options: [
      "Reduce holding to 75% or below — they already comply",
      "Reduce holding to 51%",
      "Increase holding to 75%",
      "Delist within a year",
    ],
    answer: "Reduce holding to 75% or below — they already comply",
    explanation: "Minimum public shareholding is 25%, so promoter holding must not exceed 75%. At 74% the company already complies — the question tests whether the rule is read as a ceiling on promoters rather than a floor.",
  },
  {
    topic: "taxation",
    difficulty: "medium",
    stem: "Input tax credit under GST allows a business to:",
    options: [
      "Offset GST paid on purchases against GST collected on sales",
      "Claim a refund of income tax",
      "Deduct GST from taxable profit",
      "Avoid GST on exports only",
    ],
    answer: "Offset GST paid on purchases against GST collected on sales",
    explanation: "That offset is what makes GST a tax on value added rather than on turnover, and it is why breaks in the credit chain — an unregistered supplier — are commercially costly.",
  },
  {
    topic: "banking",
    difficulty: "medium",
    stem: "The RBI's repo rate is the rate at which:",
    options: [
      "The RBI lends to commercial banks against securities",
      "Banks lend to each other overnight",
      "Banks lend to their best customers",
      "The RBI borrows from banks",
    ],
    answer: "The RBI lends to commercial banks against securities",
    explanation: "Repo is the RBI lending to banks; the reverse repo is the RBI absorbing liquidity from them. The call rate is the interbank rate.",
  },
  {
    topic: "business structures",
    difficulty: "medium",
    stem: "Under the Insolvency and Bankruptcy Code, a corporate insolvency resolution process is normally to be completed within:",
    options: ["330 days including litigation", "90 days", "One year from admission", "There is no limit"],
    answer: "330 days including litigation",
    explanation: "180 days, extendable by 90, with an outer limit of 330 days inclusive of any legal proceedings. Timeliness is the Code's central design goal because asset value decays during delay.",
  },
  {
    topic: "corporate governance",
    difficulty: "hard",
    stem: "Which committee of a listed Indian company's board must be chaired by an independent director?",
    options: ["Audit committee", "Executive committee", "Management committee", "Operations committee"],
    answer: "Audit committee",
    explanation: "The audit committee requires a majority of independent directors and an independent chair, because its job is to scrutinise management rather than to assist it.",
  },
];
