import type { ObjectiveSeed } from "./types";

/** Logical reasoning, second batch. */
export const LOGICAL_REASONING_MORE: ObjectiveSeed[] = [
  {
    topic: "blood relations",
    difficulty: "easy",
    stem: "Pointing to a man, Rhea said, \"He is the only son of my mother's father.\" How is the man related to Rhea?",
    options: ["Maternal uncle", "Father", "Brother", "Grandfather"],
    answer: "Maternal uncle",
    explanation: "Her mother's father is her grandfather. His only son is her mother's brother — her maternal uncle.",
  },
  {
    topic: "blood relations",
    difficulty: "medium",
    stem: "A is B's sister. C is B's mother. D is C's father. E is D's mother. How is A related to D?",
    options: ["Granddaughter", "Daughter", "Grandmother", "Niece"],
    answer: "Granddaughter",
    explanation: "C is A's mother (since A and B are siblings). D is C's father, so D is A's grandfather and A is his granddaughter.",
  },
  {
    topic: "coding decoding",
    difficulty: "easy",
    stem: "If MARKET is coded as NBSLFU, how is BRAND coded?",
    options: ["CSBOE", "CSBPE", "CTBOE", "BSBOE"],
    answer: "CSBOE",
    explanation: "Each letter moves forward by one. B→C, R→S, A→B, N→O, D→E gives CSBOE.",
  },
  {
    topic: "coding decoding",
    difficulty: "medium",
    stem: "If in a code LEAD is written as OHDG, how is COST written?",
    options: ["FRVW", "FRVX", "ERVW", "FSVW"],
    answer: "FRVW",
    explanation: "Each letter moves forward by three. C→F, O→R, S→V, T→W gives FRVW.",
  },
  {
    topic: "series",
    difficulty: "easy",
    stem: "What comes next: 3, 7, 15, 31, 63, ___?",
    options: ["127", "125", "126", "128"],
    answer: "127",
    explanation: "Each term is double the previous plus one: 63 × 2 + 1 = 127. Equivalently the terms are 2^n − 1.",
  },
  {
    topic: "series",
    difficulty: "medium",
    stem: "What comes next: 2, 6, 12, 20, 30, ___?",
    options: ["42", "40", "44", "36"],
    answer: "42",
    explanation: "Differences are 4, 6, 8, 10, so the next is 12: 30 + 12 = 42. Equivalently each term is n(n+1).",
  },
  {
    topic: "series",
    difficulty: "hard",
    stem: "What comes next: 1, 4, 27, 256, ___?",
    options: ["3125", "625", "1024", "3025"],
    answer: "3125",
    explanation: "Each term is n raised to itself: 1¹, 2², 3³, 4⁴, so the fifth is 5⁵ = 3,125.",
  },
  {
    topic: "arrangement",
    difficulty: "medium",
    stem: "Six people sit around a circular table facing the centre. P is second to the left of Q. R is opposite P. S is immediately right of Q. Who sits opposite S?",
    options: ["Cannot be determined", "P", "Q", "R"],
    answer: "Cannot be determined",
    explanation: "Two of the six seats are never fixed relative to S by the constraints given, so the person opposite S is not determined. Recognising an under-constrained puzzle is itself the skill being tested — candidates lose marks by forcing an answer.",
  },
  {
    topic: "syllogism",
    difficulty: "medium",
    stem: "No manager is an intern. All interns are employees. Which conclusion follows?",
    options: [
      "Some employees are not managers",
      "No employee is a manager",
      "All employees are interns",
      "Some managers are employees",
    ],
    answer: "Some employees are not managers",
    explanation: "Interns are employees and no intern is a manager, so at least those employees are not managers. The others overreach: nothing rules out managers also being employees, and nothing makes all employees interns.",
  },
  {
    topic: "assumption",
    difficulty: "medium",
    stem: "\"Our app should launch in Tier 2 cities first. Customer acquisition cost there is half of what it is in metros.\" The argument assumes:",
    options: [
      "Customers acquired in Tier 2 are worth at least as much",
      "Tier 2 cities have more smartphone users",
      "Competitors are absent from Tier 2",
      "The app works offline",
    ],
    answer: "Customers acquired in Tier 2 are worth at least as much",
    explanation: "Half the CAC is only better if lifetime value holds. If Tier 2 customers spend a quarter as much, cheap acquisition is still value-destroying. The argument is silent on the revenue side, which is exactly the gap.",
  },
  {
    topic: "strengthen and weaken",
    difficulty: "hard",
    stem: "\"Remote workers are more productive: our remote team shipped 30% more features last quarter.\" Which most weakens this?",
    options: [
      "The remote team is staffed with the company's most senior engineers",
      "Remote workers report higher job satisfaction",
      "The office team had a public holiday",
      "Feature count is rising company-wide",
    ],
    answer: "The remote team is staffed with the company's most senior engineers",
    explanation: "It offers an alternative cause for the same result — seniority, not location. A public holiday is a weaker version of the same move, and satisfaction is irrelevant to the productivity claim.",
  },
  {
    topic: "data sufficiency",
    difficulty: "hard",
    stem: "What is the company's gross margin? (1) Revenue is ₹500 crore. (2) Gross profit is ₹180 crore.",
    options: [
      "Both together are sufficient, neither alone",
      "Statement 1 alone is sufficient",
      "Statement 2 alone is sufficient",
      "Neither alone nor both together are sufficient",
    ],
    answer: "Both together are sufficient, neither alone",
    explanation: "Margin is gross profit ÷ revenue. Each statement supplies one of the two numbers and neither supplies both, so the pair is needed and is enough: 180/500 = 36%.",
  },
  {
    topic: "direction sense",
    difficulty: "easy",
    stem: "A man walks 5 km north, turns right and walks 3 km, turns right and walks 5 km. How far is he from the start?",
    options: ["3 km", "5 km", "8 km", "13 km"],
    answer: "3 km",
    explanation: "North 5, east 3, south 5. The northward and southward legs cancel, leaving him 3 km east of the start.",
  },
  {
    topic: "inference",
    difficulty: "medium",
    stem: "\"Only candidates who cleared the aptitude test were interviewed. Meera was interviewed.\" Which follows?",
    options: [
      "Meera cleared the aptitude test",
      "Meera received an offer",
      "Everyone who cleared was interviewed",
      "Meera scored highly",
    ],
    answer: "Meera cleared the aptitude test",
    explanation: "\"Only X were interviewed\" makes clearing a necessary condition for being interviewed. It does not make it sufficient, so option 3 does not follow.",
  },
];

/** Verbal, second batch. */
export const VERBAL_MORE: ObjectiveSeed[] = [
  {
    topic: "reading comprehension",
    difficulty: "medium",
    context:
      "Microfinance was sold on a simple promise: small loans would let the poor build businesses and lift themselves out of poverty. Two decades of randomised trials have found something more modest. Borrowers do start more businesses, but those businesses rarely grow, and average household income barely moves. What does change is the ability to smooth consumption — to absorb a medical bill without selling the buffalo. That is a real benefit, and a much smaller one than was promised.",
    stem: "The author's view of microfinance is best described as:",
    options: [
      "Qualified support — it works, but not in the way it was sold",
      "Outright rejection as a failed idea",
      "Enthusiastic endorsement",
      "Neutral summary with no view",
    ],
    answer: "Qualified support — it works, but not in the way it was sold",
    explanation: "The closing sentence does both jobs: \"a real benefit\" and \"much smaller than promised\". Neither rejection nor endorsement fits, and the passage plainly takes a position.",
  },
  {
    topic: "reading comprehension",
    difficulty: "hard",
    context:
      "Microfinance was sold on a simple promise: small loans would let the poor build businesses and lift themselves out of poverty. Two decades of randomised trials have found something more modest. Borrowers do start more businesses, but those businesses rarely grow, and average household income barely moves. What does change is the ability to smooth consumption — to absorb a medical bill without selling the buffalo. That is a real benefit, and a much smaller one than was promised.",
    stem: "The buffalo is mentioned in order to:",
    options: [
      "Make the abstract idea of consumption smoothing concrete",
      "Show that borrowers own livestock",
      "Argue that medical costs are the main use of loans",
      "Illustrate that businesses rarely grow",
    ],
    answer: "Make the abstract idea of consumption smoothing concrete",
    explanation: "It is an example chosen to give a technical phrase a picture. The passage makes no claim about how common livestock or medical costs are.",
  },
  {
    topic: "para jumble",
    difficulty: "medium",
    stem: "Order these into a coherent paragraph. (1) The result was a shortage that lasted two years. (2) Carmakers cancelled chip orders early in the pandemic. (3) Demand for cars recovered far faster than anyone forecast. (4) Chip foundries reallocated that capacity to consumer electronics.",
    options: ["2-4-3-1", "2-3-4-1", "3-2-4-1", "4-2-3-1"],
    answer: "2-4-3-1",
    explanation: "Cause and consequence: carmakers cancel (2), foundries reallocate (4), demand returns (3), shortage follows (1). \"That capacity\" in 4 must follow the cancellation in 2.",
  },
  {
    topic: "para completion",
    difficulty: "medium",
    stem: "\"Every firm in the sector reports a talent shortage. None has raised starting pay in three years. ___\"",
    options: [
      "It is worth asking whether the shortage is of talent or of willingness to pay for it.",
      "Talent shortages are a global phenomenon.",
      "Starting pay is set by market forces.",
      "The sector should lobby for more graduates.",
    ],
    answer: "It is worth asking whether the shortage is of talent or of willingness to pay for it.",
    explanation: "The two sentences are in tension, and the completion must acknowledge it. The others ignore the contradiction the setup deliberately creates.",
  },
  {
    topic: "usage",
    difficulty: "medium",
    stem: "Which sentence is free of error?",
    options: [
      "Neither the CEO nor the directors were aware of the clause.",
      "Neither the CEO nor the directors was aware of the clause.",
      "The committee have not yet reached a decision, and it will meet again.",
      "Each of the analysts were given a separate model.",
    ],
    answer: "Neither the CEO nor the directors were aware of the clause.",
    explanation: "With neither/nor the verb agrees with the nearer subject — \"directors\" — so \"were\" is right. Option 3 mixes plural and singular for one body; option 4 needs \"was\" after \"each\".",
  },
  {
    topic: "vocabulary in context",
    difficulty: "medium",
    stem: "\"The board's approval was perfunctory.\" This means the approval was:",
    options: [
      "Given as a formality, without real scrutiny",
      "Given enthusiastically",
      "Refused on technical grounds",
      "Delayed pending more information",
    ],
    answer: "Given as a formality, without real scrutiny",
    explanation: "Perfunctory means done as a routine duty, with minimal care or interest.",
  },
  {
    topic: "vocabulary in context",
    difficulty: "hard",
    stem: "\"The firm's growth proved ephemeral.\" The growth was:",
    options: ["Short-lived", "Extraordinary", "Hard-won", "Widely reported"],
    answer: "Short-lived",
    explanation: "Ephemeral means lasting a very short time. The sentence is a criticism dressed as a description.",
  },
  {
    topic: "summary",
    difficulty: "medium",
    stem: "Best one-line summary of: \"The merger will cut costs, but the two firms sell to the same customers, so the combined revenue will be less than the sum of the parts.\"",
    options: [
      "Cost savings are real but some revenue will be lost to overlap.",
      "The merger should not proceed.",
      "Cost savings always exceed revenue losses in mergers.",
      "The two firms have different customers.",
    ],
    answer: "Cost savings are real but some revenue will be lost to overlap.",
    explanation: "The sentence concedes the saving and raises the overlap. It stops short of recommending against the merger, so option 2 adds a judgement that is not there.",
  },
  {
    topic: "sentence correction",
    difficulty: "medium",
    stem: "Choose the best version: \"Having reviewed the model, the assumptions seemed optimistic to the analyst.\"",
    options: [
      "Having reviewed the model, the analyst found the assumptions optimistic.",
      "Having reviewed the model, the assumptions were optimistic.",
      "The assumptions, having reviewed the model, seemed optimistic.",
      "The model having been reviewed, the assumptions seemed optimistic to the analyst.",
    ],
    answer: "Having reviewed the model, the analyst found the assumptions optimistic.",
    explanation: "A dangling modifier: the assumptions did not review the model. The opening phrase must attach to the analyst.",
  },
  {
    topic: "reading comprehension",
    difficulty: "medium",
    context:
      "Indian retail has been described as 'unorganised' for so long that the word has stopped being a description and become a judgement. The kirana store survives not because it has escaped modernisation but because it offers three things organised retail has struggled to match: credit without paperwork, delivery within minutes, and an owner who knows what a household buys. Each of these is now being rebuilt, expensively, by companies that once assumed the kirana would simply disappear.",
    stem: "The author's central claim is that:",
    options: [
      "The kirana store's advantages were underestimated and are now being imitated",
      "Organised retail has failed in India",
      "Kirana stores will eventually disappear",
      "Indian retail should not be described at all",
    ],
    answer: "The kirana store's advantages were underestimated and are now being imitated",
    explanation: "The final sentence carries the argument: the things assumed to be backwardness turned out to be capabilities worth rebuilding. The passage does not predict either side's demise.",
  },
];
