-- ============================================================================
-- Cloud SQL — all 75 RLS policies, ported off auth.uid()
-- ============================================================================
-- GENERATED by scripts/gcp/generate-rls-port.sql from the live Supabase
-- catalogue. Do not hand-edit: change the policy on Supabase, re-run the
-- generator, and diff. Every `auth.uid()` became `app.current_user_id()`; the
-- predicates are otherwise byte-identical to production.
--
-- Policies are granted `to casecode_app` rather than the Supabase-era
-- anon/authenticated pair. casecode_admin holds BYPASSRLS and is not listed.
-- ============================================================================

drop policy if exists "achievements are public" on public.achievements;
create policy "achievements are public" on public.achievements as permissive for select to casecode_app
  using (true);
drop policy if exists "students read their own, teachers read the class" on public.assignment_submissions;
create policy "students read their own, teachers read the class" on public.assignment_submissions as permissive for select to casecode_app
  using (((user_id = app.current_user_id()) OR (EXISTS ( SELECT 1
   FROM classroom_assignments a
  WHERE ((a.id = assignment_submissions.assignment_id) AND is_classroom_teacher(a.classroom_id))))));
drop policy if exists "admins manage badges" on public.badges;
create policy "admins manage badges" on public.badges as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "badges are public" on public.badges;
create policy "badges are public" on public.badges as permissive for select to casecode_app
  using (true);
drop policy if exists "own bookmarks are deletable" on public.bookmarks;
create policy "own bookmarks are deletable" on public.bookmarks as permissive for delete to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "own bookmarks are insertable" on public.bookmarks;
create policy "own bookmarks are insertable" on public.bookmarks as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "own bookmarks are readable" on public.bookmarks;
create policy "own bookmarks are readable" on public.bookmarks as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins manage categories" on public.case_categories;
create policy "admins manage categories" on public.case_categories as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "categories are public" on public.case_categories;
create policy "categories are public" on public.case_categories as permissive for select to casecode_app
  using (true);
drop policy if exists "admins manage hints" on public.case_hints;
create policy "admins manage hints" on public.case_hints as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "hints are public" on public.case_hints;
create policy "hints are public" on public.case_hints as permissive for select to casecode_app
  using (true);
drop policy if exists "admins resolve reports" on public.case_reports;
create policy "admins resolve reports" on public.case_reports as permissive for update to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "own reports are insertable" on public.case_reports;
create policy "own reports are insertable" on public.case_reports as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "own reports are readable" on public.case_reports;
create policy "own reports are readable" on public.case_reports as permissive for select to casecode_app
  using (((app.current_user_id() = user_id) OR is_admin()));
drop policy if exists "admins manage cases" on public.cases;
create policy "admins manage cases" on public.cases as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "published cases are public" on public.cases;
create policy "published cases are public" on public.cases as permissive for select to casecode_app
  using ((is_admin() OR (is_published AND ((visibility = 'platform'::case_visibility) OR (created_by = app.current_user_id()) OR ((owner_classroom_id IS NOT NULL) AND is_classroom_member(owner_classroom_id)) OR (EXISTS ( SELECT 1
   FROM classroom_assignments a
  WHERE ((a.case_id = cases.id) AND a.is_published AND a.is_public)))))));
drop policy if exists "own chat messages" on public.chat_messages;
create policy "own chat messages" on public.chat_messages as permissive for select to casecode_app
  using ((EXISTS ( SELECT 1
   FROM chat_sessions s
  WHERE ((s.id = chat_messages.session_id) AND (s.user_id = app.current_user_id())))));
drop policy if exists "own chat sessions" on public.chat_sessions;
create policy "own chat sessions" on public.chat_sessions as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "members read published assignments" on public.classroom_assignments;
create policy "members read published assignments" on public.classroom_assignments as permissive for select to casecode_app
  using ((is_classroom_teacher(classroom_id) OR (is_published AND is_classroom_member(classroom_id)) OR (is_published AND is_public)));
drop policy if exists "members read the roster" on public.classroom_members;
create policy "members read the roster" on public.classroom_members as permissive for select to casecode_app
  using (is_classroom_member(classroom_id));
drop policy if exists "members read their classroom" on public.classrooms;
create policy "members read their classroom" on public.classrooms as permissive for select to casecode_app
  using ((is_classroom_member(id) OR (owner_id = app.current_user_id())));
drop policy if exists "users cast their own comment votes" on public.comment_votes;
create policy "users cast their own comment votes" on public.comment_votes as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "users retract their own comment votes" on public.comment_votes;
create policy "users retract their own comment votes" on public.comment_votes as permissive for delete to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "votes are public" on public.comment_votes;
create policy "votes are public" on public.comment_votes as permissive for select to casecode_app
  using (true);
drop policy if exists "authenticated users write comments" on public.comments;
create policy "authenticated users write comments" on public.comments as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "comments are public" on public.comments;
create policy "comments are public" on public.comments as permissive for select to casecode_app
  using (((NOT is_deleted) OR is_admin()));
drop policy if exists "users delete their own comments" on public.comments;
create policy "users delete their own comments" on public.comments as permissive for delete to casecode_app
  using (((app.current_user_id() = user_id) OR is_admin()));
drop policy if exists "users edit their own comments" on public.comments;
create policy "users edit their own comments" on public.comments as permissive for update to casecode_app
  using ((app.current_user_id() = user_id))
  with check ((app.current_user_id() = user_id));
drop policy if exists "admins read all contest entries" on public.contest_submissions;
create policy "admins read all contest entries" on public.contest_submissions as permissive for select to casecode_app
  using (is_admin());
drop policy if exists "finished contest entries are public" on public.contest_submissions;
create policy "finished contest entries are public" on public.contest_submissions as permissive for select to casecode_app
  using ((EXISTS ( SELECT 1
   FROM contests c
  WHERE ((c.id = contest_submissions.contest_id) AND (c.status = 'completed'::contest_status)))));
drop policy if exists "users read their own contest entries" on public.contest_submissions;
create policy "users read their own contest entries" on public.contest_submissions as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins manage contests" on public.contests;
create policy "admins manage contests" on public.contests as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "published contests are public" on public.contests;
create policy "published contests are public" on public.contests as permissive for select to casecode_app
  using ((is_published OR is_admin()));
drop policy if exists "own drill attempts are readable" on public.drill_attempts;
create policy "own drill attempts are readable" on public.drill_attempts as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins manage drill questions" on public.drill_questions;
create policy "admins manage drill questions" on public.drill_questions as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "drill questions are public" on public.drill_questions;
create policy "drill questions are public" on public.drill_questions as permissive for select to casecode_app
  using (true);
drop policy if exists "group roster visible to members" on public.group_members;
create policy "group roster visible to members" on public.group_members as permissive for select to casecode_app
  using (is_group_member(group_id));
drop policy if exists "group posts follow group visibility" on public.group_posts;
create policy "group posts follow group visibility" on public.group_posts as permissive for select to casecode_app
  using ((EXISTS ( SELECT 1
   FROM groups g
  WHERE ((g.id = group_posts.group_id) AND ((NOT g.is_private) OR is_group_member(g.id))))));
drop policy if exists "public groups are visible" on public.groups;
create policy "public groups are visible" on public.groups as permissive for select to casecode_app
  using (((NOT is_private) OR is_group_member(id)));
drop policy if exists "own reveals are insertable" on public.hint_reveals;
create policy "own reveals are insertable" on public.hint_reveals as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "own reveals are readable" on public.hint_reveals;
create policy "own reveals are readable" on public.hint_reveals as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "staff read the roster" on public.institution_members;
create policy "staff read the roster" on public.institution_members as permissive for select to casecode_app
  using ((is_institution_staff(institution_id) OR (user_id = app.current_user_id())));
drop policy if exists "members read their institution" on public.institutions;
create policy "members read their institution" on public.institutions as permissive for select to casecode_app
  using ((institution_role_of(id) IS NOT NULL));
drop policy if exists "leaderboards are public" on public.leaderboards;
create policy "leaderboards are public" on public.leaderboards as permissive for select to casecode_app
  using (true);
drop policy if exists "admins manage path steps" on public.learning_path_steps;
create policy "admins manage path steps" on public.learning_path_steps as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "path steps are public" on public.learning_path_steps;
create policy "path steps are public" on public.learning_path_steps as permissive for select to casecode_app
  using (true);
drop policy if exists "admins manage paths" on public.learning_paths;
create policy "admins manage paths" on public.learning_paths as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "paths are public" on public.learning_paths;
create policy "paths are public" on public.learning_paths as permissive for select to casecode_app
  using ((is_published OR is_admin()));
drop policy if exists "own model attempts are readable" on public.model_attempts;
create policy "own model attempts are readable" on public.model_attempts as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins manage model cells" on public.model_cells;
create policy "admins manage model cells" on public.model_cells as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "model cells are public" on public.model_cells;
create policy "model cells are public" on public.model_cells as permissive for select to casecode_app
  using (true);
drop policy if exists "own notifications are readable" on public.notifications;
create policy "own notifications are readable" on public.notifications as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "own notifications are updatable" on public.notifications;
create policy "own notifications are updatable" on public.notifications as permissive for update to casecode_app
  using ((app.current_user_id() = user_id))
  with check ((app.current_user_id() = user_id));
drop policy if exists "admins manage rubrics" on public.rubrics;
create policy "admins manage rubrics" on public.rubrics as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "rubrics readable for published cases" on public.rubrics;
create policy "rubrics readable for published cases" on public.rubrics as permissive for select to casecode_app
  using ((EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = rubrics.case_id) AND (is_admin() OR (c.is_published AND ((c.visibility = 'platform'::case_visibility) OR (c.created_by = app.current_user_id()) OR ((c.owner_classroom_id IS NOT NULL) AND is_classroom_member(c.owner_classroom_id)))))))));
drop policy if exists "admins read all scores" on public.scores;
create policy "admins read all scores" on public.scores as permissive for select to casecode_app
  using (is_admin());
drop policy if exists "scores on public solutions are readable" on public.scores;
create policy "scores on public solutions are readable" on public.scores as permissive for select to casecode_app
  using ((EXISTS ( SELECT 1
   FROM submissions s
  WHERE ((s.id = scores.submission_id) AND s.is_public))));
drop policy if exists "users read their own scores" on public.scores;
create policy "users read their own scores" on public.scores as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "submission votes are public" on public.submission_votes;
create policy "submission votes are public" on public.submission_votes as permissive for select to casecode_app
  using (true);
drop policy if exists "users cast their own submission votes" on public.submission_votes;
create policy "users cast their own submission votes" on public.submission_votes as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "users retract their own submission votes" on public.submission_votes;
create policy "users retract their own submission votes" on public.submission_votes as permissive for delete to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins read all submissions" on public.submissions;
create policy "admins read all submissions" on public.submissions as permissive for select to casecode_app
  using (is_admin());
drop policy if exists "public solutions are readable" on public.submissions;
create policy "public solutions are readable" on public.submissions as permissive for select to casecode_app
  using ((is_public AND (status = 'evaluated'::submission_status)));
drop policy if exists "users create their own submissions" on public.submissions;
create policy "users create their own submissions" on public.submissions as permissive for insert to casecode_app
  with check ((app.current_user_id() = user_id));
drop policy if exists "users delete their own submissions" on public.submissions;
create policy "users delete their own submissions" on public.submissions as permissive for delete to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "users read their own submissions" on public.submissions;
create policy "users read their own submissions" on public.submissions as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "users update their own submissions" on public.submissions;
create policy "users update their own submissions" on public.submissions as permissive for update to casecode_app
  using ((app.current_user_id() = user_id))
  with check ((app.current_user_id() = user_id));
drop policy if exists "own subscriptions" on public.subscriptions;
create policy "own subscriptions" on public.subscriptions as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins manage universities" on public.universities;
create policy "admins manage universities" on public.universities as permissive for all to casecode_app
  using (is_admin())
  with check (is_admin());
drop policy if exists "universities are public" on public.universities;
create policy "universities are public" on public.universities as permissive for select to casecode_app
  using (true);
drop policy if exists "users read their own activity" on public.user_activity;
create policy "users read their own activity" on public.user_activity as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "users read their own path progress" on public.user_path_progress;
create policy "users read their own path progress" on public.user_path_progress as permissive for select to casecode_app
  using ((app.current_user_id() = user_id));
drop policy if exists "admins can update any profile" on public.users;
create policy "admins can update any profile" on public.users as permissive for update to casecode_app
  using (is_admin());
drop policy if exists "users are readable by everyone" on public.users;
create policy "users are readable by everyone" on public.users as permissive for select to casecode_app
  using (true);
drop policy if exists "users can update their own profile" on public.users;
create policy "users can update their own profile" on public.users as permissive for update to casecode_app
  using ((app.current_user_id() = id))
  with check ((app.current_user_id() = id));
