/**
 * Seeds the case library.
 *
 *   npm run seed          # write to the database
 *   npm run seed:dry      # generate and validate, write nothing
 *
 * Idempotent: cases are upserted on `slug`, so re-running updates rows in place
 * rather than creating duplicates. Requires SUPABASE_SERVICE_ROLE_KEY because
 * it writes tables that RLS reserves for admins.
 */

import { writeFileSync } from "node:fs";
import { config } from "dotenv";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../src/lib/types/database";
import { expand, type Archetype } from "./lib/generator";
import { FINANCE_ARCHETYPES } from "./templates/finance";
import { CONSULTING_ARCHETYPES } from "./templates/consulting";
import { PRODUCT_ARCHETYPES } from "./templates/product";
import { STRATEGY_ARCHETYPES } from "./templates/strategy";
import { MARKETING_ARCHETYPES } from "./templates/marketing";
import { OPERATIONS_ARCHETYPES } from "./templates/operations";
import { DEBUG_ARCHETYPES } from "./templates/debug";

config({ path: ".env.local" });
config({ path: ".env" });

const DRY_RUN = process.argv.includes("--dry-run");

/**
 * Emits an idempotent .sql file instead of writing over the network. Lets the
 * library be seeded from the Supabase SQL editor, so no service-role key has
 * to leave the dashboard.
 */
const EMIT_SQL = process.argv.includes("--emit-sql");
const SQL_OUT = "supabase/seed/cases.sql";

const PLAN = [
  { archetypes: FINANCE_ARCHETYPES, count: 100, seed: 1_000, label: "Finance" },
  { archetypes: CONSULTING_ARCHETYPES, count: 100, seed: 2_000, label: "Consulting" },
  { archetypes: PRODUCT_ARCHETYPES, count: 100, seed: 3_000, label: "Product Management" },
  { archetypes: STRATEGY_ARCHETYPES, count: 60, seed: 4_000, label: "Strategy" },
  { archetypes: MARKETING_ARCHETYPES, count: 60, seed: 5_000, label: "Marketing" },
  { archetypes: OPERATIONS_ARCHETYPES, count: 60, seed: 6_000, label: "Operations" },
  { archetypes: DEBUG_ARCHETYPES, count: 24, seed: 7_000, label: "Debug" },
];

/**
 * Difficulty is rotated across variants so each domain spans the full range,
 * anchored on the archetype's natural difficulty. The ladders are weighted to
 * land the library near a 20/55/25 easy/medium/hard split — enough easy cases
 * for a first session, without the catalogue skewing hard.
 */
function difficultyFor(archetype: Archetype, index: number) {
  const LADDERS = {
    easy: ["easy", "easy", "easy", "medium", "medium"],
    medium: ["easy", "medium", "medium", "medium", "hard"],
    hard: ["hard", "medium", "hard", "medium", "medium"],
  } as const;

  const ladder = LADDERS[archetype.difficulty];
  return ladder[index % ladder.length];
}

const TRACKS: Record<string, string[]> = {
  "finance-track": [
    "statement-diagnosis-1",
    "statement-diagnosis-2",
    "comps-valuation-1",
    "npv-irr-project-1",
    "npv-irr-project-2",
    "capital-raise-1",
    "comps-valuation-2",
    "dcf-valuation-1",
    "capital-raise-2",
    "dcf-valuation-2",
    "ma-accretion-1",
    "ma-accretion-2",
  ],
  "consulting-track": [
    "market-sizing-1",
    "market-sizing-2",
    "profitability-decline-1",
    "profitability-decline-2",
    "market-entry-1",
    "growth-strategy-1",
    "operations-capacity-1",
    "market-entry-2",
    "growth-strategy-2",
    "pricing-strategy-1",
    "operations-capacity-2",
    "pricing-strategy-2",
  ],
  "product-management-track": [
    "metric-drop-1",
    "prioritization-1",
    "metric-drop-2",
    "product-launch-1",
    "prioritization-2",
    "retention-diagnosis-1",
    "product-launch-2",
    "growth-loop-1",
    "retention-diagnosis-2",
    "growth-loop-2",
  ],
};


/** Single-quote escaping for SQL string literals. */
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return "'" + value.replace(/'/g, "''") + "'";
}

function jsonLit(value: unknown): string {
  return lit(JSON.stringify(value ?? {})) + "::jsonb";
}

function textArrayLit(values: string[]): string {
  if (values.length === 0) return "'{}'::text[]";
  return "ARRAY[" + values.map(lit).join(",") + "]::text[]";
}

type SeedCase = {
  slug: string;
  title: string;
  domain: string;
  difficulty: string;
  category_slug: string;
  company_track: string;
  estimated_minutes: number;
  scenario: string;
  instructions: string;
  supporting_data: Record<string, unknown>;
  expected_framework: string;
  model_answer: string;
  tags: string[];
  is_published: boolean;
  rubric: Archetype["rubric"];
};

/**
 * Renders the whole library as one idempotent transaction. Rows are keyed on
 * natural keys (slug) and every foreign key is resolved with a subselect, so
 * the file never hardcodes a generated id and can be re-run safely.
 */
function buildSql(allCases: SeedCase[]): string {
  const out: string[] = [
    "-- Generated by `npm run seed:sql`. Do not edit by hand.",
    `-- ${allCases.length} cases, their rubrics, and the learning-path steps.`,
    "BEGIN;",
    "",
  ];

  for (const item of allCases) {
    out.push(
      "INSERT INTO cases (slug, title, domain, difficulty, category_id, company_track, " +
        "estimated_minutes, scenario, instructions, supporting_data, expected_framework, " +
        "model_answer, tags, is_published) VALUES (",
      "  " +
        [
          lit(item.slug),
          lit(item.title),
          `${lit(item.domain)}::domain`,
          `${lit(item.difficulty)}::difficulty`,
          `(SELECT id FROM case_categories WHERE slug = ${lit(item.category_slug)})`,
          lit(item.company_track),
          String(item.estimated_minutes),
          lit(item.scenario),
          lit(item.instructions),
          jsonLit(item.supporting_data),
          lit(item.expected_framework),
          lit(item.model_answer),
          textArrayLit(item.tags),
          String(item.is_published),
        ].join(", "),
      ") ON CONFLICT (slug) DO UPDATE SET",
      "  title = EXCLUDED.title, domain = EXCLUDED.domain, difficulty = EXCLUDED.difficulty,",
      "  category_id = EXCLUDED.category_id, company_track = EXCLUDED.company_track,",
      "  estimated_minutes = EXCLUDED.estimated_minutes, scenario = EXCLUDED.scenario,",
      "  instructions = EXCLUDED.instructions, supporting_data = EXCLUDED.supporting_data,",
      "  expected_framework = EXCLUDED.expected_framework, model_answer = EXCLUDED.model_answer,",
      "  tags = EXCLUDED.tags, is_published = EXCLUDED.is_published, updated_at = now();",
      "",
    );

    const maxScore = Object.values(item.rubric.criteria).reduce(
      (a, b) => a + b,
      0,
    );

    out.push(
      "INSERT INTO rubrics (case_id, criteria, descriptors, max_score, pass_score) VALUES (",
      "  " +
        [
          `(SELECT id FROM cases WHERE slug = ${lit(item.slug)})`,
          jsonLit(item.rubric.criteria),
          jsonLit(item.rubric.descriptors),
          String(maxScore),
          String(item.rubric.passScore),
        ].join(", "),
      ") ON CONFLICT (case_id) DO UPDATE SET",
      "  criteria = EXCLUDED.criteria, descriptors = EXCLUDED.descriptors,",
      "  max_score = EXCLUDED.max_score, pass_score = EXCLUDED.pass_score, updated_at = now();",
      "",
    );
  }

  // Rebuilt from scratch, exactly as the network path does, so a re-run can
  // never leave a stale step behind.
  const trackSlugs = Object.keys(TRACKS).map(lit).join(", ");
  out.push(
    `DELETE FROM learning_path_steps WHERE path_id IN (SELECT id FROM learning_paths WHERE slug IN (${trackSlugs}));`,
    "",
  );

  for (const [pathSlug, caseSlugs] of Object.entries(TRACKS)) {
    caseSlugs.forEach((caseSlug, index) => {
      out.push(
        "INSERT INTO learning_path_steps (path_id, case_id, step_order, title, unlock_threshold)",
        "SELECT " +
          [
            `p.id`,
            `c.id`,
            String(index + 1),
            lit(caseSlug.replace(/-\d+$/, "").replace(/-/g, " ")),
            "60",
          ].join(", "),
        `FROM learning_paths p, cases c WHERE p.slug = ${lit(pathSlug)} AND c.slug = ${lit(caseSlug)};`,
        "",
      );
    });
  }

  out.push("COMMIT;", "");
  return out.join("\n");
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!DRY_RUN && !EMIT_SQL && (!url || !key)) {
    console.error(
      "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.\n" +
        "Copy .env.example to .env.local and fill them in, or run with --dry-run.",
    );
    process.exit(1);
  }

  const supabase =
    DRY_RUN || EMIT_SQL || !url || !key
      ? null
      : createClient<Database>(url, key, {
          auth: { autoRefreshToken: false, persistSession: false },
        });

  // ---- category lookup ---------------------------------------------------
  let categoryBySlug = new Map<string, string>();
  if (supabase) {
    const { data, error } = await supabase
      .from("case_categories")
      .select("id, slug");

    if (error) {
      console.error("Could not read case_categories:", error.message);
      console.error("Have you applied the migrations in supabase/migrations?");
      process.exit(1);
    }

    categoryBySlug = new Map((data ?? []).map((row) => [row.slug, row.id]));

    if (categoryBySlug.size === 0) {
      console.error(
        "No categories found. Apply 20250101000003_reference_data.sql first.",
      );
      process.exit(1);
    }
  }

  // ---- generate ----------------------------------------------------------
  const allCases: Array<{
    slug: string;
    title: string;
    domain: string;
    difficulty: string;
    category_id: string | null;
    category_slug: string;
    format: string;
    company_track: string;
    estimated_minutes: number;
    scenario: string;
    instructions: string;
    supporting_data: Record<string, unknown>;
    expected_framework: string;
    model_answer: string;
    tags: string[];
    is_published: boolean;
    rubric: Archetype["rubric"];
  }> = [];

  for (const group of PLAN) {
    const generated = expand(group.archetypes, group.count, group.seed);

    generated.forEach((item, index) => {
      allCases.push({
        slug: item.slug,
        title: item.title,
        domain: item.archetype.domain,
        difficulty: difficultyFor(item.archetype, index),
        category_id: categoryBySlug.get(item.archetype.categorySlug) ?? null,
        category_slug: item.archetype.categorySlug,
        company_track: item.companyTrack,
        estimated_minutes: item.archetype.estimatedMinutes,
        scenario: item.scenario,
        instructions: item.instructions,
        supporting_data: item.supportingData,
        expected_framework: item.expectedFramework,
        model_answer: item.modelAnswer,
        tags: item.archetype.tags,
        is_published: true,
        // Debug archetypes are ids prefixed "debug-"; everything else the
        // generator produces is a full case.
        format: item.archetype.id.startsWith("debug-") ? "debug" : "full_case",
        rubric: item.archetype.rubric,
      });
    });

    console.log(`Generated ${generated.length} ${group.label} cases`);
  }

  // ---- validate ----------------------------------------------------------
  const problems: string[] = [];
  const seen = new Set<string>();

  for (const item of allCases) {
    if (seen.has(item.slug)) problems.push(`duplicate slug: ${item.slug}`);
    seen.add(item.slug);

    if (item.scenario.length < 200)
      problems.push(`${item.slug}: scenario too short`);
    if (!item.model_answer || item.model_answer.length < 200)
      problems.push(`${item.slug}: model answer too short`);

    const weights = Object.values(item.rubric.criteria);
    if (weights.length === 0) problems.push(`${item.slug}: empty rubric`);
    if (weights.some((w) => !Number.isInteger(w) || w <= 0))
      problems.push(`${item.slug}: invalid rubric weight`);

    // Catch template interpolation that failed, without tripping on prose
    // that legitimately uses the word — a debug case explaining that a broken
    // terminal value is "undefined" is correct, not a bug.
    //
    // A failed interpolation always lands where a value was expected, so it
    // shows up glued to a currency symbol, a digit, or a unit. NaN is never
    // legitimate prose, so it is flagged unconditionally.
    const interpolationFailure =
      /[₹$€£¥]\s*undefined|undefined\s*(?:Cr|M|B|units|months)\b|undefined\s*[%×]|\bNaN\b/;

    if (interpolationFailure.test(item.scenario))
      problems.push(`${item.slug}: scenario contains a failed interpolation`);
    if (interpolationFailure.test(item.model_answer))
      problems.push(`${item.slug}: model answer contains a failed interpolation`);
  }

  if (problems.length > 0) {
    console.error(`\n${problems.length} validation problems:`);
    problems.slice(0, 25).forEach((p) => console.error("  " + p));
    process.exit(1);
  }

  console.log(`\nValidated ${allCases.length} cases with no problems.`);

  const byDifficulty = allCases.reduce<Record<string, number>>((acc, item) => {
    acc[item.difficulty] = (acc[item.difficulty] ?? 0) + 1;
    return acc;
  }, {});
  console.log("Difficulty spread:", byDifficulty);

  if (EMIT_SQL) {
    writeFileSync(SQL_OUT, buildSql(allCases));
    console.log(`\nWrote ${SQL_OUT} — run it in the Supabase SQL editor.`);
    return;
  }

  if (DRY_RUN || !supabase) {
    console.log("\nDry run — nothing written.");
    console.log("\nSample case:\n");
    console.log(JSON.stringify(allCases[0], null, 2).slice(0, 1800) + "\n…");
    return;
  }

  // ---- write cases -------------------------------------------------------
  console.log("\nWriting cases…");
  const CHUNK = 50;
  const caseIdBySlug = new Map<string, string>();

  for (let i = 0; i < allCases.length; i += CHUNK) {
    const chunk = allCases.slice(i, i + CHUNK);
    const { data, error } = await supabase
      .from("cases")
      .upsert(
        chunk.map((item) => {
          const { rubric, category_slug, ...fields } = item;
          void rubric;
          void category_slug;
          return fields;
        }),
        { onConflict: "slug" },
      )
      .select("id, slug");

    if (error) {
      console.error("Case upsert failed:", error.message);
      process.exit(1);
    }

    for (const row of data ?? []) caseIdBySlug.set(row.slug, row.id);
    console.log(`  ${Math.min(i + CHUNK, allCases.length)}/${allCases.length}`);
  }

  // ---- write rubrics -----------------------------------------------------
  console.log("Writing rubrics…");
  const rubricRows = allCases
    .map((item) => {
      const caseId = caseIdBySlug.get(item.slug);
      if (!caseId) return null;
      return {
        case_id: caseId,
        criteria: item.rubric.criteria,
        descriptors: item.rubric.descriptors,
        max_score: Object.values(item.rubric.criteria).reduce((a, b) => a + b, 0),
        pass_score: item.rubric.passScore,
      };
    })
    .filter((row): row is NonNullable<typeof row> => row !== null);

  for (let i = 0; i < rubricRows.length; i += CHUNK) {
    const { error } = await supabase
      .from("rubrics")
      .upsert(rubricRows.slice(i, i + CHUNK), { onConflict: "case_id" });

    if (error) {
      console.error("Rubric upsert failed:", error.message);
      process.exit(1);
    }
  }

  // ---- wire learning paths ----------------------------------------------
  console.log("Wiring learning path steps…");
  await wireLearningPaths(supabase, caseIdBySlug);

  console.log(`\nDone. ${allCases.length} cases and rubrics are live.`);
}

/**
 * Builds each track from the generated cases, ordered easy → hard so the
 * unlock sequence is a real difficulty ramp.
 */
async function wireLearningPaths(
  supabase: ReturnType<typeof createClient<Database>>,
  caseIdBySlug: Map<string, string>,
) {

  const { data: paths } = await supabase
    .from("learning_paths")
    .select("id, slug");

  const pathIdBySlug = new Map((paths ?? []).map((p) => [p.slug, p.id]));

  for (const [pathSlug, caseSlugs] of Object.entries(TRACKS)) {
    const pathId = pathIdBySlug.get(pathSlug);
    if (!pathId) {
      console.warn(`  skipping ${pathSlug} — path not found`);
      continue;
    }

    // Rebuild the track from scratch so re-seeding cannot leave stale steps.
    await supabase.from("learning_path_steps").delete().eq("path_id", pathId);

    const steps = caseSlugs
      .map((slug, index) => {
        const caseId = caseIdBySlug.get(slug);
        if (!caseId) return null;
        return {
          path_id: pathId,
          case_id: caseId,
          step_order: index + 1,
          title: slug.replace(/-\d+$/, "").replace(/-/g, " "),
          unlock_threshold: 60,
        };
      })
      .filter((row): row is NonNullable<typeof row> => row !== null);

    if (steps.length === 0) continue;

    const { error } = await supabase.from("learning_path_steps").insert(steps);
    if (error) {
      console.error(`  ${pathSlug}: ${error.message}`);
    } else {
      console.log(`  ${pathSlug}: ${steps.length} steps`);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
